name: Ingest

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: databricks/setup-cli@main

      - name: Run ingestion job
        run: databricks bundle run ingestion_job -t dev

      - name: Run transform job
        run: databricks bundle run transform_job -t dev
